kind: Service
apiVersion: v1
metadata:
  name: prueba-backend
spec:
  selector:
    app: prueba-backend
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-backend
spec:
  selector:
      matchLabels:
        app: prueba-backend
        tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: prueba-backend
        tier: backend
    spec:
      containers:
        - name: prueba-backend
          image: prueba-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

